Add TestRunner

diff --git a/oyster b/oyster
--- a/oyster
+++ b/oyster
@@ -20,27 +20,31 @@ fi
 # display usage
 usage() {
     local func info
-    [ "$APP_PATH" = "$OYST_PATH/modules" ] && modules=true
 
-    echo ""
-    echo "Usage: "
+    if [ -n "$SELF" ]; then
+        echo ""
+        echo "Usage: "
 
-    while read -r LINE; do
-        func="${LINE// /}"
-        func="${func%%(*}"
-        info=$(grep -C0 -A0 -B1 "^$func *() *{" "$APP_PATH/$SELF" | sed "N;s/\n.*//g")
-        if [ "$modules" = true ]; then
-            printf "    %-20s %-40s\n" "$func" "$info" | grep "#"
-        else
-            printf "    ./$SELF %-20s %-40s\n" "$func" "$info" | grep "#"
-        fi
-    done < <(grep "^[^_].\+() *{$" "$APP_PATH/$SELF")
-    echo ""
-    echo "oyster shell script framework library:"
-    echo ""
-    echo "    ENVIRONMENT: ${ENVIRONMENT:=(not specified)}"
-    echo "    APP_PATH:    $APP_PATH"
-    echo "    OYST_PATH:   $OYST_PATH"
+        [ "$APP_PATH" = "$OYST_PATH/modules" ] && modules=true
+        while read -r LINE; do
+            func="${LINE// /}"
+            func="${func%%(*}"
+            info=$(grep -C0 -A0 -B1 "^$func *() *{" "$APP_PATH/$SELF" | sed "N;s/\n.*//g")
+            if [ "$modules" = true ]; then
+                printf "    %-20s %-40s\n" "$func" "$info" | grep "#"
+            else
+                printf "    ./$SELF %-20s %-40s\n" "$func" "$info" | grep "#"
+            fi
+        done < <(grep "^[^_].\+() *{$" "$APP_PATH/$SELF")
+    else
+        echo ""
+        echo "oyster shell script framework library:"
+        echo ""
+        echo "    ENVIRONMENT:      ${ENVIRONMENT:=(not specified)}"
+        [ "$APP_PATH" = "$OYST_PATH" ] || echo "    APP_PATH:         $APP_PATH"
+        echo "    OYST_PATH:        $OYST_PATH"
+        [ -n "$OYST_MODULE_PATH" ] && echo "    OYST_MODULE_PATH: $OYST_MODULE_PATH"
+    fi
     echo ""
 }
 
@@ -116,6 +120,7 @@ require() {
 
 # import <module-name1> <module-name2> ...
 import() {
+    local module
     for module in "${@}"; do
         local oyster_module="${OYST_MODULE_PATH:-OYST_PATH/modules}/${module}"
         local app_module="${APP_PATH}/modules/${module}"
@@ -138,24 +143,33 @@ import() {
     fi
 }
 
-# load main script
-{
-    if [ -f "$1" ]; then
-        source "$1"
-        shift
+if [ "$SELF" = "test" ]; then
 
-        # debug on
-        [ -n "${DEBUG:-}" ] && set -x
+    # load test script
+    cd tests || die "tests directory not found."
+    while read -r TEST_MODULE; do
+        oyster "$TEST_MODULE" run
+    done < <(ls -1)
+    cd ..
 
-        # execute command
-        "$@" || die "execute '$1'."
+else
 
-        # debug off
-        [ -n "${DEBUG:-}" ] && set +x
-    fi
+    # load main script
+        if [ -f "$1" ]; then
+            source "$1"
+            shift
 
-}
+            # debug on
+            [ -n "${DEBUG:-}" ] && set -x
 
-[ -z "${SELF}" ] && ok "hello oyster!"
+            # execute command
+            "$@" || die "execute '$1'."
+
+            # debug off
+            [ -n "${DEBUG:-}" ] && set +x
+        fi
+
+    [ -z "${SELF}" ] && usage
+fi
 
 exit 0
